name: mbankingflutter
description: MBankingFlutter.
version: 1.0.9+9
environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  barcode_widget: ^2.0.4
  cached_network_image: ^3.2.3
  carousel_slider: ^5.0.0
  client_information: ^2.1.4
  collection: ^1.16.0
  connectivity_plus: ^6.0.3
  crclib: ^3.0.0
  crypto: ^3.0.2
  encrypt: ^5.0.1
  file: ^7.0.0
  fl_chart: ^0.68.0
  flash: ^3.0.5+1
  flutter_jailbreak_detection: ^1.10.0
  flutter_secure_storage: ^9.0.0
  flutter_svg:
  flutter_widget_from_html: ^0.15.2
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.2.1
  get: ^4.6.5
  hex: ^0.2.0
  http: ^1.2.0
  image: ^4.0.17
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.7
  intl: ^0.19.0
  json_sorter: ^1.0.0
  local_auth: ^2.1.8
  mobile_scanner: ^5.1.0
  package_info_plus: ^8.0.0
  path: ^1.8.1
  path_provider: ^2.0.11
  pdfx: ^2.6.0
  permission_handler: ^11.3.1
  qr_flutter: ^4.0.0
  remove: ^1.0.10
  screenshot: ^3.0.0
  share_plus: ^9.0.0
  shared_preferences: ^2.1.1
  smooth_page_indicator: ^1.0.0+2
  sqflite: ^2.3.0
  uuid: ^4.4.0
  webview_flutter: ^4.4.4
  xor_cipher: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/contracts/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
